name: NodeJS with Webpack

on: all
  push:Potentia
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:Potentia
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ Potentia}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ Potentia}}

    - name: Build
      run: |
        npm install
        npx webpack
